### PR TITLE
Update for v1.59

### PR DESCRIPTION
**Pull request by hackape**
Hey evan, could you please update the npm package? I make it work with Vimium v1.59.

### CODE REVIEW

**Comment by EvanHahn** [comment]
Instead of me merging this PR, would you like to take over the project?

**Comment by hackape** [comment]
Ok, I can do that.

**Comment by EvanHahn** [comment]
Please shoot me an email at me@evanhahn.com and we can get the project transferred over to you.

**Comment by hackape** [comment]
email shot.

**Pull request merged**
